### ISSUE TITLE
kx-3553/3552 installation failed with "kX device not found" message

### ISSUE THREAD

**Issue by mole2old** [kxproject/kx-audio-driver#16] opened 2018-03-31 12:07 UTC
Target OS: Windows 7x64 Professional (UAC disabled, SecureBoot Disabled)
1. [kx-3553 installation debug log (pastebin)](https://pastebin.com/yrgA4gk3)
2. Additional [screenshots part #1 (imgur)](https://imgur.com/a/bNE19)
2. Additional [screenshots part #2 (imgur)](https://imgur.com/a/OByrv)
**To E. Gavrilov:** see PM (Conversations) on [hardwareheaven forum](http://www.hardwareheaven.com/community/threads/windows-10-and-kx-3552-new-fix.230567/), we have а good news.

**Comment by flood404** [comment] 2018-04-01 04:26
The kx-3553 driver is not signed.  Windows will not load unsigned drivers if secure boot is enabled in BIOS.  Or if you do not disable  driver signature enforcement at every boot.    I have the 3553 working in windows 10 pro with  secure boot disabled. I did not have to do anything else. I have abandoned windows 7 since windows 10 came out.

**Comment by mole2old** [comment] 2018-04-01 07:31
In my case SecureBoot always disabled in BIOS.

**Comment by flood404** [comment] 2018-04-01 14:28
Ok and its also possible some program is detecting the Kx.sys as a trojan and deleting it.  I wonder if you make  ky.sys as read only so it can't be deleted.    Also if you need the driver for the gameport I have that one which is what the PCI input device you have listed in there.

**Comment by flood404** [comment] 2018-04-02 14:16
I just updated to the windows 10 1803 17133 version the driver is still loading fine for me.

**Comment by Proshaa** [comment] 2018-04-03 18:29
подтверждаю - всё выглядит именно так, как на представленных скринах. ОС 8.1х64 Ent, SecureBoot отключен, UAC отключен, Defender в ручном режиме, других антивирусов нет.
установить драйвер (3553) с помощью kxsetup.exe получилось только включив режим совместимости с Win7 для всех ехе и нескольких перезагрузок. 
кроме того, при первой установке версии 3551 пришлось добавить рег-файл с ассоциациями, иначе не взлетало.

**Comment by flood404** [comment] 2018-04-03 19:56
I did have the version 3552 installed and just installed the 3553 without uninstalling the 3552 version.

Я установил версию 3552 и установил 3553 без удаления версии 3552.
YA ustanovil versiyu 3552 i ustanovil 3553 bez udaleniya versii 3552.

**Comment by kxproject** [comment] 2018-04-17 17:05
Issue should be fixed in the latest commit.

**Closed by kxproject** 2018-04-17 17:05 UTC

**Comment by kreksoverzum** [comment] 2020-03-23 15:17
Just in case if it helps in the future: I ran into the same issue when installed kxdrv3553-full-unsigned.exe.
I fixed the error the same way mole2old did, but before that i noticed that in Sysinternal's Autoruns utility the driver location was set to "system32\drivers\kx.sys" instead of "C:\Windows\system32\drivers\kx.sys" and therefore was not loaded. 
Because i hope the problem is solved and because I have no ability to build and test the latest trunk i decided not to post a new issue.
![image](https://user-images.githubusercontent.com/2082796/77330361-4e6f5b80-6d30-11ea-8cfb-2c3ee0d7024e.png)
